# Base image is node-version 18.17.1
#??
# update OS, install bash and clean all installation files
#??
    #??
    #??
# create directory server and ...
#??
# set it as working directory
#??
# copy all local files in the backend into
# working directory
#??
# install all nodejs dependencies
#??
# expose port 3000 of the app
#??
# run server
#??

